apiVersion: v1
kind: Pod
metadata: 
  name: questbook-ui-2
  labels: 
    app: questbook-ui
spec:
  containers: 
    - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
      imagePullPolicy: IfNotPresent
      name: questbook-ui
      ports: 
        - name: http
          containerPort: 80
          protocol: TCP
  restartPolicy: Always