apiVersion: v1
kind: Service
metadata: 
  name: questbook-ui
spec:
  ports: 
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: questbook-ui
  type: LoadBalancer